-- 200 FAQ mới cho Meow Garden — import vào DB sau faq_seed.sql
-- Kiểm tra: 200 entries, mỗi entry có Question + Answer + Category
SET NOCOUNT ON;

INSERT INTO Faqs (Question, Answer, Category, IsActive, CreatedAt, UpdatedAt) VALUES

-- ============================================================
-- CHÍNH SÁCH (25 FAQ) — category: 'policy'
-- ============================================================

(N'Mèo mua về có được bảo hành sức khỏe không?', N'Meow Garden bảo hành sức khỏe mèo trong 7 ngày kể từ ngày nhận bé. Nếu mèo có biểu hiện bệnh lý do nguyên nhân tồn tại trước khi giao như virus, nấm, ký sinh trùng được xác nhận bởi bác sĩ thú y có giấy tờ, shop sẽ hỗ trợ một phần hoặc toàn bộ chi phí điều trị, hoặc đổi bé khác tùy từng trường hợp cụ thể. Để được hỗ trợ, bạn cần giữ hóa đơn mua hàng, đưa bé đến phòng khám thú y trong vòng 7 ngày và gửi kết quả chẩn đoán về cho shop. Điều kiện áp dụng là bé được chăm sóc đúng theo hướng dẫn của shop, không bị thay đổi môi trường quá đột ngột. Liên hệ hotline hoặc fanpage ngay khi phát hiện bé có vấn đề bạn nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có cam kết nguồn gốc mèo rõ ràng không?', N'Meow Garden cam kết 100% mèo bán ra có nguồn gốc rõ ràng từ các trại giống uy tín trong nước, được kiểm tra sức khỏe định kỳ bởi bác sĩ thú y trước khi bán. Mỗi bé đều có hồ sơ theo dõi sức khỏe cá nhân, ghi rõ ngày sinh, giống, lịch sử tiêm phòng và tẩy giun. Shop không nhập mèo từ nguồn không rõ ràng, không tái xuất mèo bệnh. Khi mua bạn sẽ nhận được phiếu theo dõi sức khỏe kèm theo. Nếu cần thêm thông tin về trại giống hoặc bố mẹ của bé, bạn có thể yêu cầu shop cung cấp ảnh và thông tin bổ sung. Sự minh bạch là cam kết hàng đầu của Meow Garden nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mèo bị bệnh ngay sau khi mua phải làm gì?', N'Nếu mèo có dấu hiệu bệnh trong vòng 7 ngày sau khi nhận, bạn cần làm ngay các bước sau: Thứ nhất, đưa bé đến bác sĩ thú y gần nhất để được chẩn đoán và giữ lại toàn bộ giấy tờ kết quả khám. Thứ hai, chụp ảnh hoặc quay video các triệu chứng bé đang gặp phải. Thứ ba, liên hệ ngay với shop qua fanpage hoặc Zalo kèm ảnh mèo, hóa đơn mua hàng và giấy tờ y tế. Shop sẽ xem xét từng trường hợp cụ thể và có phương án hỗ trợ phù hợp. Không tự ý điều trị hoặc cho bé uống thuốc không có chỉ định của bác sĩ trước khi liên hệ shop bạn nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Chính sách đặt cọc mèo tại Meow Garden như thế nào?', N'Khi đặt cọc mèo tại Meow Garden, bạn cần thanh toán trước 30-50% giá trị bé để giữ chỗ. Sau khi đặt cọc, bé sẽ được giữ riêng cho bạn và không bán cho người khác. Thời gian giữ cọc tối đa là 14 ngày kể từ ngày đặt, sau đó bạn cần thanh toán phần còn lại và nhận bé. Nếu cần gia hạn thêm, hãy báo trước ít nhất 2 ngày. Đặt cọc có thể thực hiện qua chuyển khoản ngân hàng hoặc VietQR trên website. Sau khi xác nhận đặt cọc, bạn sẽ nhận được biên lai điện tử qua email hoặc Zalo nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Đặt cọc xong nhưng không lấy mèo nữa có hoàn tiền không?', N'Theo chính sách của Meow Garden, tiền cọc sẽ không được hoàn trả nếu bạn chủ động hủy đặt mèo sau khi đã xác nhận. Đây là điều khoản cần thiết để shop bảo đảm quản lý tốt đàn mèo và không gây thiệt hại cho trại giống. Tuy nhiên, nếu lý do hủy đến từ phía shop (ví dụ bé bị bệnh, bé không đạt tiêu chuẩn) thì toàn bộ tiền cọc sẽ được hoàn trả 100% trong vòng 3-5 ngày làm việc. Nếu bạn có tình huống đặc biệt như ốm đau hoặc sự cố bất khả kháng, hãy liên hệ trực tiếp với shop để được xem xét từng trường hợp cụ thể. Shop luôn cố gắng hỗ trợ tốt nhất trong khả năng bạn nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop đặt cọc mèo rồi nhưng bé bị ốm không giao được thì sao?', N'Nếu bé mèo bạn đặt cọc bị ốm và chưa thể giao đúng thời hạn, Meow Garden sẽ chủ động liên hệ thông báo ngay cho bạn và đưa ra hai lựa chọn. Một là chờ bé khỏe bệnh hoàn toàn rồi nhận, thời gian gia hạn không tính thêm phí giữ cọc. Hai là chọn bé khác có sẵn trong shop với mức giá tương đương, phần chênh lệch sẽ được điều chỉnh hợp lý. Ba là hoàn trả toàn bộ tiền cọc nếu bạn không muốn chờ hoặc không có bé phù hợp. Shop cam kết không để bạn chịu thiệt hại khi sự cố đến từ phía Meow Garden. Minh bạch và trách nhiệm là điều shop luôn đặt lên hàng đầu nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mèo nhận về không giống mô tả trên website phải làm gì?', N'Nếu bé mèo bạn nhận về có màu lông, giới tính hoặc đặc điểm khác so với mô tả trên website hoặc trong tư vấn, hãy chụp ảnh và video ngay khi nhận bé và liên hệ shop trong vòng 24 giờ. Shop sẽ xem xét và đối chiếu thông tin đã cung cấp. Nếu xác nhận có sai sót từ phía shop, bạn sẽ được đổi bé đúng theo yêu cầu hoặc hoàn tiền đầy đủ bao gồm cả phí vận chuyển. Shop sẽ không tranh luận hay yêu cầu bạn giữ bé không đúng ý. Để tránh hiểu nhầm, trước khi đặt hàng bạn nên yêu cầu video call xem bé trực tiếp, shop luôn sẵn sàng hỗ trợ bạn nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có nhận lại mèo nếu tôi không nuôi được không?', N'Meow Garden không có chính sách nhận lại mèo sau khi bán ra vì mỗi bé cần môi trường ổn định và không bị thay đổi chủ liên tục điều này ảnh hưởng đến tâm lý bé rất nhiều. Tuy nhiên, shop có thể hỗ trợ bạn tìm gia đình mới phù hợp thông qua mạng lưới khách hàng và cộng đồng mèo của shop. Bạn cần cam kết chăm sóc bé cho đến khi tìm được nhà mới và không bỏ bé ra đường hoặc đưa vào trung tâm không uy tín. Nếu bạn đang gặp khó khăn trong việc nuôi mèo, hãy nhắn tin cho shop để được tư vấn và hỗ trợ tìm giải pháp phù hợp nhất nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có cung cấp giấy chứng nhận tiêm phòng mèo không?', N'Có bạn nhé! Tất cả mèo bán ra tại Meow Garden đều được tiêm phòng đầy đủ trước khi giao cho khách và có sổ theo dõi tiêm phòng đi kèm. Sổ này ghi rõ ngày tiêm, loại vaccine đã sử dụng, tên phòng khám thú y thực hiện, và lịch tiêm nhắc lại tiếp theo để bạn tiện theo dõi. Đối với mèo con dưới 8 tuần chưa đủ tuổi tiêm mũi đầu, shop sẽ cung cấp phiếu hẹn tiêm tại phòng khám đối tác và hướng dẫn chi tiết lịch tiêm cho bé. Giấy chứng nhận tiêm phòng là tài liệu quan trọng cần giữ lại để theo dõi sức khỏe bé lâu dài nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có hợp đồng mua bán mèo bằng văn bản không?', N'Meow Garden có biên bản xác nhận giao nhận mèo đối với các đơn hàng trực tiếp tại shop hoặc theo yêu cầu của khách hàng. Biên bản ghi rõ thông tin bé mèo bao gồm giống, màu lông, giới tính, tuổi, tình trạng sức khỏe tại thời điểm giao, cùng với cam kết bảo hành sức khỏe 7 ngày và các điều khoản liên quan. Đối với đơn hàng online, xác nhận đặt hàng qua email hoặc Zalo được coi là bằng chứng giao dịch hợp lệ. Nếu bạn cần hợp đồng chính thức có chữ ký và đóng dấu cho mục đích đặc biệt, hãy liên hệ trực tiếp với shop để được sắp xếp nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Chính sách hoàn tiền mèo cảnh như thế nào?', N'Meow Garden áp dụng chính sách hoàn tiền đầy đủ trong các trường hợp sau: bé mèo bị bệnh nặng không thể điều trị được xác nhận bởi bác sĩ thú y trong vòng 7 ngày sau khi nhận, bé mèo không đúng giống hoặc giới tính như đã cam kết, hoặc bé tử vong trong quá trình vận chuyển do lỗi từ phía shop. Quy trình hoàn tiền: bạn gửi đầy đủ hồ sơ bao gồm hóa đơn, kết quả khám thú y và ảnh video chứng minh về shop trong vòng 24 giờ. Shop sẽ xem xét và phản hồi trong 48 giờ làm việc. Tiền hoàn trả về tài khoản ngân hàng trong 3-7 ngày làm việc nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Bảo hành phụ kiện điện tử như máy cho ăn tự động bao lâu?', N'Tại Meow Garden, các sản phẩm điện tử như máy tự động cho ăn, máy lọc nước uống tự động, đèn UV diệt khuẩn được bảo hành từ 3 đến 6 tháng tùy hãng sản xuất. Trong thời gian bảo hành, nếu sản phẩm bị lỗi kỹ thuật do nhà sản xuất mà không phải do va đập hoặc sử dụng sai cách, shop sẽ đổi mới hoặc sửa chữa miễn phí. Bạn cần giữ hộp và phiếu bảo hành khi mua. Đối với phụ kiện vải, đồ chơi và dây kéo, shop hỗ trợ đổi mới trong 3 ngày đầu nếu phát hiện lỗi sản xuất. Liên hệ shop kèm ảnh sản phẩm lỗi để được xử lý nhanh nhất nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Khiếu nại về mèo hoặc sản phẩm gửi về đâu?', N'Bạn có thể gửi khiếu nại về mèo hoặc sản phẩm qua các kênh sau của Meow Garden: nhắn tin trực tiếp qua fanpage Facebook, Zalo OA của shop để được phản hồi trong vòng 2 giờ trong giờ làm việc 8h-21h. Hoặc gửi email với đầy đủ thông tin: tên, số điện thoại, mã đơn hàng, mô tả vấn đề và ảnh/video minh chứng. Shop cam kết phản hồi mọi khiếu nại trong vòng 24 giờ làm việc và giải quyết dứt điểm trong tối đa 7 ngày làm việc. Đối với trường hợp khẩn cấp liên quan đến sức khỏe mèo, hãy gọi điện trực tiếp để được hỗ trợ ngay lập tức nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mua mèo trực tiếp tại shop và mua online có chính sách khác nhau không?', N'Chính sách bảo hành và hỗ trợ sau bán hàng của Meow Garden áp dụng như nhau cho cả hai hình thức. Khi mua trực tiếp tại shop, bạn có thể xem và tương tác với bé trước khi quyết định, giảm thiểu rủi ro. Khi mua online, shop hỗ trợ video call xem bé trực tiếp trước khi đặt cọc để đảm bảo bạn thấy đúng bé muốn mua. Cả hai hình thức đều nhận được phiếu theo dõi sức khỏe, lịch tiêm phòng và bảo hành 7 ngày. Điểm khác biệt là khi mua online bạn cần chịu thêm phí vận chuyển và có thể mất thêm 1-3 ngày để nhận bé. Shop luôn ưu tiên đảm bảo quyền lợi của khách dù mua theo hình thức nào nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có cam kết mèo không mắc bệnh FIP trước khi bán không?', N'Meow Garden thực hiện kiểm tra sức khỏe toàn diện cho mèo trước khi bán, bao gồm xét nghiệm máu cơ bản và tình trạng lâm sàng tổng quát. Tuy nhiên, FIP là bệnh rất khó phát hiện sớm vì virus corona ở mèo phổ biến và chỉ một số ít trường hợp đột biến thành FIP. Không có xét nghiệm nào 100% loại trừ nguy cơ FIP hoàn toàn. Nếu mèo phát triển triệu chứng FIP trong vòng 30 ngày sau khi mua và được xác nhận bởi bác sĩ thú y, shop sẽ xem xét hỗ trợ chi phí điều trị hoặc đổi bé tùy từng trường hợp cụ thể. Hãy liên hệ shop ngay khi phát hiện triệu chứng bất thường nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mua mèo có kèm phụ kiện cơ bản không hay phải mua thêm?', N'Khi mua mèo tại Meow Garden, bé sẽ đến kèm theo một túi thức ăn dùng trong 3-5 ngày đầu giúp bé chuyển tiếp chế độ ăn quen thuộc tránh tiêu chảy do thay đổi đột ngột. Ngoài ra bé có sổ tiêm phòng, giấy tờ sức khỏe và hướng dẫn chăm sóc tại nhà. Phụ kiện như khay cát, thức ăn dài hạn, đồ chơi không bao gồm trong giá mèo nhưng bạn có thể mua kèm tại shop với giá ưu đãi khi mua combo. Shop khuyến nghị chuẩn bị đầy đủ đồ dùng cơ bản trước khi đón bé về để bé có môi trường thoải mái nhất ngay từ ngày đầu nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Nếu mèo chết trong vòng 7 ngày bảo hành shop xử lý thế nào?', N'Đây là tình huống rất đáng tiếc và shop hiểu được nỗi mất mát của bạn. Nếu mèo tử vong trong vòng 7 ngày bảo hành, bạn cần đưa bé đến phòng khám thú y để xác định nguyên nhân tử vong và giữ lại giấy tờ chứng nhận. Nếu nguyên nhân được xác định là bệnh lý tồn tại trước khi giao như virus, vi khuẩn, suy nội tạng bẩm sinh và không liên quan đến tai nạn hoặc chăm sóc sai cách, shop sẽ đổi bé mới hoặc hoàn tiền đầy đủ. Liên hệ shop trong vòng 24 giờ sau khi sự việc xảy ra. Shop cam kết xử lý nhân văn và trách nhiệm trong mọi tình huống nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Có thể đặt trước mèo chưa ra đời theo giống yêu cầu không?', N'Meow Garden nhận đặt trước mèo theo giống yêu cầu trong trường hợp hiện tại không có sẵn. Bạn cần đặt cọc 20-30% giá dự kiến để giữ chỗ. Shop sẽ thông báo khi có lứa mới phù hợp và bạn có quyền ưu tiên chọn bé trước khi mở bán rộng rãi. Thời gian chờ đợi thường từ 1-3 tháng tùy giống và mùa sinh sản. Trong thời gian chờ, shop sẽ cập nhật thường xuyên qua Zalo về tiến triển của lứa. Nếu không có bé phù hợp sau thời gian chờ thỏa thuận, tiền cọc sẽ được hoàn trả đầy đủ. Hãy nhắn shop để biết thêm về các giống đang chờ nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có chính sách riêng cho khách mua lần đầu không?', N'Khách mua mèo lần đầu tại Meow Garden được hỗ trợ đặc biệt bao gồm: tư vấn miễn phí qua Zalo trong suốt 30 ngày đầu nuôi bé về các vấn đề chăm sóc, dinh dưỡng và sức khỏe. Shop cũng tặng kèm tài liệu hướng dẫn chăm sóc mèo dành cho người mới và danh sách phòng khám thú y uy tín gần nhất. Ngoài ra, khách mới thường xuyên nhận được mã giảm giá cho lần mua phụ kiện tiếp theo. Mục tiêu của shop là đảm bảo cả bạn lẫn bé mèo đều có khởi đầu tốt nhất có thể. Đừng ngại hỏi bất kỳ điều gì dù nhỏ nhất, shop luôn sẵn sàng hỗ trợ nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có nhận đặt hàng mèo theo đặc điểm cụ thể như màu mắt màu lông không?', N'Meow Garden có thể nhận đơn đặt mèo với đặc điểm cụ thể như màu lông, màu mắt hoặc hoa văn theo yêu cầu. Tuy nhiên, bạn cần hiểu rằng mèo là sinh vật sống nên không thể đảm bảo 100% đặc điểm theo yêu cầu do gen di truyền không hoàn toàn có thể kiểm soát. Shop sẽ tìm kiếm và thông báo khi có bé gần đúng với yêu cầu nhất. Tiền cọc sẽ không bị mất nếu bé không đạt đúng yêu cầu và bạn không muốn chọn bé đó. Thời gian chờ đợi cho đặt hàng theo yêu cầu đặc biệt thường dài hơn từ 2-6 tháng. Nhắn shop để trao đổi chi tiết hơn nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Chính sách đổi mèo sang giống khác có được không?', N'Meow Garden không hỗ trợ đổi mèo sang giống khác sau khi đã hoàn tất giao dịch vì mỗi bé là cá thể sống cần được ổn định với gia đình. Tuy nhiên nếu bạn chưa nhận bé và muốn thay đổi giống, có thể điều chỉnh đơn trước khi giao nếu shop có sẵn giống phù hợp, phần chênh lệch giá sẽ được tính toán lại. Trường hợp bé đã về nhà nhưng bạn thực sự không phù hợp, shop có thể hỗ trợ tìm gia đình mới và tư vấn bạn chọn giống phù hợp hơn khi mua bé tiếp theo. Trước khi mua shop luôn khuyến nghị tìm hiểu kỹ về giống mèo để tránh hối tiếc về sau nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Khi mèo bị bệnh sau khi mua tôi nên đến phòng khám nào?', N'Meow Garden có danh sách các phòng khám thú y uy tín đối tác tại Hà Nội và TP.HCM sẽ được cung cấp kèm khi bạn nhận bé. Các phòng khám đối tác đã quen với các giống mèo cảnh phổ biến và có kinh nghiệm xử lý các bệnh đặc thù. Khi đến khám, hãy mang theo sổ tiêm phòng và giấy tờ mua hàng của bé để bác sĩ có đủ thông tin nền. Ngoài ra, bạn có thể hỏi shop để được tư vấn phòng khám phù hợp nhất với địa điểm của bạn. Trong trường hợp khẩn cấp ngoài giờ làm việc, shop có thể tư vấn phòng khám cấp cứu 24/7 gần nhất. Đừng chờ đợi khi thấy bé có dấu hiệu bất thường nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có xác nhận giống thuần chủng không?', N'Meow Garden cung cấp mèo giống thuần chủng từ trại giống có uy tín với hồ sơ gia phả và lý lịch bố mẹ rõ ràng. Đối với các giống cao cấp như Ragdoll, Bengal, Maine Coon, shop có thể cung cấp giấy tờ xác nhận từ trại giống bao gồm ảnh bố mẹ và thông tin dòng dõi. Tuy nhiên không phải tất cả mèo đều được đăng ký với hiệp hội giống quốc tế vì chi phí rất cao và thủ tục phức tạp tại Việt Nam. Shop cam kết mô tả đúng đặc điểm giống và không gian lận về xuất xứ. Nếu bạn cần chứng nhận giống cụ thể cho mục đích đặc biệt, hãy hỏi trước khi đặt mua nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Sau khi hết 7 ngày bảo hành mèo bị bệnh shop có hỗ trợ gì không?', N'Sau 7 ngày bảo hành chính thức, Meow Garden không còn trách nhiệm về chi phí điều trị bệnh lý mới phát sinh. Tuy nhiên shop vẫn cam kết hỗ trợ bạn về mặt thông tin và tư vấn miễn phí trong suốt quá trình nuôi bé. Bạn có thể nhắn tin hỏi shop về triệu chứng, thuốc cần mua hoặc khi nào cần đi khám để có định hướng ban đầu. Shop cũng sẽ giới thiệu bác sĩ thú y phù hợp nếu bạn cần. Sau 30 ngày nuôi bé, bạn có thể tham gia nhóm cộng đồng khách hàng Meow Garden để hỏi kinh nghiệm từ những người nuôi mèo cùng giống. Sự hỗ trợ dài hạn là cam kết của shop với mỗi khách hàng nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có chính sách ưu đãi cho khách hàng thân thiết không?', N'Meow Garden có chương trình ưu đãi dành cho khách hàng thân thiết. Cụ thể, khách mua từ lần thứ 2 trở đi được giảm 5% giá phụ kiện và thức ăn. Khách giới thiệu bạn bè mua thành công nhận voucher giảm giá cho lần mua tiếp theo. Ngoài ra, shop thường xuyên có chương trình ưu đãi theo mùa vụ, tháng đặc biệt và sự kiện được thông báo qua fanpage. Để nhận thông tin ưu đãi sớm nhất, hãy theo dõi fanpage Facebook và Zalo OA của Meow Garden. Khách hàng đã mua mèo tại shop cũng được ưu tiên tư vấn miễn phí và hỗ trợ nhanh hơn khi có nhu cầu nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mèo mua tại shop có được tiêm phòng đủ mũi chưa hay vẫn phải tiêm thêm?', N'Mèo tại Meow Garden thường được tiêm mũi 1 vaccine 3 bệnh khi đủ 8-9 tuần tuổi. Khi bé về nhà bạn, thông thường bé chưa hoàn thành đủ phác đồ vì cần tiêm tiếp mũi 2 sau 3-4 tuần và mũi 3 sau đó 3-4 tuần nữa. Shop sẽ ghi rõ trong sổ tiêm phòng lịch các mũi cần tiêm tiếp theo. Bạn cần chủ động đưa bé đến phòng khám thú y đúng lịch để hoàn thiện phác đồ. Vaccine phòng dại cũng nên tiêm khi bé được 12-16 tuần tuổi. Tiêm đầy đủ là cách bảo vệ bé hiệu quả nhất trước các bệnh nguy hiểm. Shop sẵn sàng nhắc lịch tiêm cho bạn qua Zalo nếu cần nhé!', N'policy', 1, GETUTCDATE(), GETUTCDATE()),

-- ============================================================
-- VẬN CHUYỂN (25 FAQ) — category: 'shipping'
-- ============================================================

(N'Shop có ship mèo sống ra các tỉnh thành toàn quốc không?', N'Meow Garden có ship mèo sống đến các tỉnh thành trong cả nước bạn nhé. Tuy nhiên việc vận chuyển mèo sống phức tạp hơn hàng hóa thông thường nên shop chỉ thực hiện với mèo đã đủ sức khỏe, ít nhất 8-10 tuần tuổi và đã tiêm mũi vaccine đầu tiên. Với khách ở Hà Nội và TP.HCM, shop ưu tiên giao tận tay để đảm bảo an toàn cho bé. Với các tỉnh xa, shop sẽ tư vấn phương án vận chuyển phù hợp nhất tùy khoảng cách và mùa trong năm. Mùa hè nắng nóng shop có thể giới hạn ship đường dài để bảo vệ sức khỏe bé. Liên hệ shop để biết chi tiết cho khu vực của bạn nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mèo được vận chuyển bằng phương tiện gì khi ship tỉnh xa?', N'Meow Garden sử dụng dịch vụ vận chuyển thú cưng chuyên dụng hoặc giao qua xe khách liên tỉnh cho các tỉnh xa. Với khoảng cách dưới 500km, shop sử dụng xe khách có điều hòa và thời gian di chuyển dưới 8 tiếng để đảm bảo bé không bị stress quá mức. Với khoảng cách xa hơn, shop có thể sắp xếp vận chuyển hàng không nếu cần thiết với chi phí bổ sung. Mèo được đặt trong lồng vận chuyển chuyên dụng có thông gió tốt, kèm thức ăn và nước uống đủ cho hành trình. Shop sẽ theo dõi và cập nhật tình trạng bé cho bạn trong quá trình vận chuyển. Bạn cần chuẩn bị lồng đón tiếp bé khi nhận nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Ship mèo đường dài có ảnh hưởng đến sức khỏe bé không?', N'Vận chuyển đường dài có thể gây stress nhẹ cho mèo nhưng nếu được chuẩn bị đúng cách thì bé sẽ phục hồi nhanh sau khi về đến nhà mới. Meow Garden chuẩn bị bé trước khi ship bao gồm không cho ăn no ngay trước chuyến đi để tránh nôn, cho vào lồng quen thuộc có mùi quen và đảm bảo bé được nghỉ ngơi đủ. Trong hành trình, nhiệt độ và thông thoáng được kiểm soát chặt chẽ. Sau khi nhận bé, bạn nên để bé trong phòng yên tĩnh vài giờ để bé điều chỉnh. Không ép bé ăn hoặc chơi ngay, cứ để bé tự khám phá dần. Hầu hết mèo sẽ bình thường trở lại sau 24-48 giờ nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Cần chuẩn bị gì trước khi nhận mèo ship đến nhà?', N'Trước khi nhận mèo, bạn cần chuẩn bị sẵn một căn phòng nhỏ yên tĩnh làm nơi bé thích nghi trong 3-5 ngày đầu với đầy đủ khay cát, bát nước, bát thức ăn và chỗ ẩn náu như thùng carton có lỗ. Chuẩn bị sẵn loại thức ăn shop đã dùng cho bé để tránh tiêu chảy do thay đổi đột ngột. Đặt sẵn nhiệt kế thú y và số điện thoại bác sĩ thú y gần nhất. Vệ sinh sạch phòng và đảm bảo không có vật nguy hiểm như dây điện thòng hoặc cây độc. Khi nhận bé hãy kiểm tra tình trạng sức khỏe ngay và quay video làm bằng chứng. Liên hệ shop ngay nếu có bất kỳ lo ngại nào nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Nhận mèo ship về xong cần làm gì ngay lập tức?', N'Ngay khi nhận mèo, bạn cần thực hiện các bước sau theo thứ tự. Đầu tiên kiểm tra tình trạng bé qua lưới lồng trước khi mở ra, quan sát xem bé có bị thương hoặc có dấu hiệu bất thường không và ghi lại bằng video. Sau đó đặt lồng vào phòng đã chuẩn bị sẵn, mở cửa lồng và để bé tự bước ra theo ý muốn, không kéo bé ra bằng lực. Đặt sẵn bát nước cho bé uống sau hành trình dài. Cho bé thời gian khám phá phòng trong yên tĩnh từ 2-4 giờ. Sau đó mới cung cấp thức ăn và bắt đầu tiếp cận nhẹ nhàng. Đừng để trẻ nhỏ hoặc nhiều người xúm lại ngay nhé, bé cần thời gian thích nghi!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Phí vận chuyển mèo sống tính thế nào?', N'Phí vận chuyển mèo sống tại Meow Garden tính theo khoảng cách và phương thức vận chuyển. Nội thành Hà Nội và TP.HCM: shop giao tận tay, phí 50-100k tùy quận. Các tỉnh miền Bắc và miền Nam gần: 150-300k qua xe khách hoặc dịch vụ chuyển phát thú cưng. Các tỉnh miền Trung và xa: 300-500k, thời gian 1-2 ngày. Vận chuyển hàng không: giá thỏa thuận tùy hãng bay, thường 500k-1.5 triệu chưa kể phụ phí hàng không. Giá có thể thay đổi theo mùa và tình hình thực tế. Shop sẽ báo giá cụ thể dựa trên địa chỉ của bạn trước khi xác nhận đơn hàng nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có cam kết nếu mèo tử vong trong quá trình vận chuyển không?', N'Meow Garden cam kết trách nhiệm hoàn toàn nếu mèo tử vong trong quá trình vận chuyển do lỗi của shop hoặc đơn vị vận chuyển. Trong trường hợp này, shop sẽ đổi bé tương đương hoặc hoàn tiền đầy đủ bao gồm cả phí vận chuyển. Để đảm bảo quyền lợi, khi nhận bé bạn cần kiểm tra ngay và quay video tình trạng bé lúc mở lồng. Nếu có bất thường hãy gọi điện cho shop ngay lập tức. Để giảm thiểu rủi ro shop chỉ ship mèo khi điều kiện thời tiết và sức khỏe bé đảm bảo, đồng thời sử dụng đơn vị vận chuyển có kinh nghiệm về thú sống. An toàn của bé luôn là ưu tiên số một nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mèo nhận về thấy mệt bỏ ăn sau khi vận chuyển phải làm gì?', N'Mệt mỏi và bỏ ăn 12-24 giờ sau khi vận chuyển là hoàn toàn bình thường do stress hành trình. Bạn cần để bé trong phòng yên tĩnh, không ồn ào, không ánh đèn chói. Cung cấp nước sạch và thức ăn quen thuộc nhưng không ép bé ăn. Bé sẽ tự ăn khi đói và đã bình tĩnh hơn. Nếu sau 48 giờ bé vẫn không ăn gì và có thêm triệu chứng như tiêu chảy, nôn hoặc thở gấp thì cần đưa đi khám ngay. Liên hệ shop song song để được tư vấn. Thông thường bé phục hồi hoàn toàn sau 2-3 ngày khi đã quen với môi trường mới. Kiên nhẫn và nhẹ nhàng là chìa khóa giúp bé thích nghi nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mèo con mấy tháng tuổi mới được phép ship đường dài?', N'Meow Garden chỉ ship mèo con đi tỉnh xa khi bé đã đủ 10-12 tuần tuổi và đã tiêm ít nhất mũi vaccine đầu tiên, hoàn toàn dứt sữa, ăn thức ăn cứng độc lập và có sức khỏe ổn định. Mèo con quá nhỏ chưa đủ sức đề kháng và dễ bị stress nghiêm trọng trong hành trình dài. Với khách ở tỉnh xa muốn nhận mèo nhỏ hơn, shop có thể giữ bé thêm vài tuần và giao khi bé đủ điều kiện, chi phí giữ bé thêm sẽ được thỏa thuận cụ thể. An toàn và sức khỏe của bé luôn được đặt lên hàng đầu, shop không ship bé chưa đủ điều kiện dù khách yêu cầu nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Có thể đến shop trực tiếp lấy mèo không cần ship không?', N'Hoàn toàn có thể và shop khuyến khích khách đến trực tiếp nếu điều kiện cho phép vì đây là cách tốt nhất để bạn gặp gỡ và chọn bé phù hợp. Địa chỉ shop và giờ mở cửa bạn có thể xem trên website hoặc fanpage Meow Garden. Nên hẹn trước qua điện thoại hoặc Zalo để đảm bảo bé bạn muốn xem vẫn còn và có nhân viên tư vấn phục vụ. Khi đến shop trực tiếp bạn có thể tương tác và xem tính cách của nhiều bé, hỏi trực tiếp về sức khỏe và lịch sử từng bé. Shop cũng hỗ trợ khách mang theo lồng sẵn để đưa bé về an toàn ngay trong ngày nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có giao mèo tận nhà tại Hà Nội không?', N'Có bạn nhé! Meow Garden hỗ trợ giao mèo tận tay tại Hà Nội bao gồm tất cả các quận nội thành và nhiều huyện ngoại thành. Nhân viên shop sẽ mang bé đến tận địa điểm bạn yêu cầu, thường trong ngày hoặc hôm sau tùy lịch. Khi giao tận tay, nhân viên sẽ hướng dẫn trực tiếp cách chăm sóc ban đầu và bàn giao đầy đủ giấy tờ kèm theo bé. Phí giao tận nhà trong nội thành dao động 50-80k tùy khoảng cách. Đơn đặt trước 14h thường được giao trong ngày. Liên hệ shop để đặt lịch giao cụ thể theo thời gian bạn tiện nhất nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có giao mèo tận nhà tại TP.HCM không?', N'Meow Garden hỗ trợ giao mèo tận tay tại TP.HCM với dịch vụ tương tự Hà Nội. Nhân viên giao hàng có kinh nghiệm vận chuyển thú sống sẽ mang bé đến tận địa chỉ của bạn. Thời gian giao thường trong ngày với đơn đặt trước 14h hoặc hôm sau. Phí giao tận nhà trong nội thành TP.HCM 50-100k tùy quận. Các khu vực ngoại thành như Bình Chánh, Củ Chi, Hóc Môn sẽ được báo giá riêng. Khi nhận bé, nhân viên sẽ bàn giao đầy đủ giấy tờ và hướng dẫn chăm sóc cơ bản. Đặc biệt mùa hè giao giờ sáng sớm hoặc chiều mát để bé không bị nóng trong quá trình di chuyển nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mùa hè nóng shop có ship mèo không?', N'Meow Garden thực hiện ship mèo quanh năm nhưng mùa hè từ tháng 5-8 sẽ có một số hạn chế để bảo vệ sức khỏe bé. Cụ thể, shop không ship đường dài quá 300km trong thời điểm nhiệt độ ngoài trời trên 37 độ C. Với khu vực nội thành, shop ưu tiên giao vào buổi sáng sớm trước 10h hoặc buổi chiều sau 17h để tránh nắng gắt. Phương tiện vận chuyển đều có điều hòa hoặc thông gió tốt. Shop sẽ tư vấn thời điểm giao phù hợp nhất khi bạn đặt hàng vào mùa hè. Sức khỏe và an toàn của bé luôn được ưu tiên hơn tiến độ giao hàng nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Nếu nhận mèo thấy bé bị thương phải làm gì ngay?', N'Nếu khi nhận mèo bạn phát hiện bé có dấu hiệu bị thương như trầy xước, chảy máu, đi khập khiễng hoặc có vết thương rõ ràng, hãy thực hiện ngay các bước sau. Trước tiên quay video tình trạng bé ngay tại chỗ trước khi mở lồng hoàn toàn. Sau đó gọi điện ngay cho shop và gửi video để thông báo. Nếu vết thương nghiêm trọng hãy đưa bé đến phòng khám thú y gần nhất ngay lập tức và gửi hóa đơn điều trị cho shop. Shop sẽ chịu hoàn toàn chi phí điều trị nếu xác nhận thương tích xảy ra trong quá trình vận chuyển. Không ký nhận hàng bình thường nếu phát hiện bé có vấn đề, hãy ghi chú vào phiếu giao hàng nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mèo bị stress sau khi vận chuyển biểu hiện như thế nào và làm sao giúp bé?', N'Mèo stress sau vận chuyển thường biểu hiện bằng việc trốn vào góc khuất, không ăn không uống trong 12-24 giờ, thở gấp nhẹ, mắt mở to hoặc ngược lại nhắm mắt thu mình. Đây là phản ứng hoàn toàn bình thường. Để giúp bé vượt qua giai đoạn này, bạn cần cung cấp không gian yên tĩnh không có tiếng ồn lớn, ánh sáng không quá chói. Đặt khay cát và bát nước trong tầm với của bé. Không bế hoặc ôm bé khi chưa đồng ý. Ngồi gần bé nói chuyện nhẹ nhàng để bé quen giọng bạn. Đặt quần áo bạn đã mặc gần chỗ bé ngủ để bé quen mùi. Hầu hết bé hồi phục hoàn toàn sau 24-72 giờ nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Có thể theo dõi đơn hàng mèo đang giao không?', N'Với đơn giao nội thành, nhân viên giao hàng sẽ chủ động nhắn tin cho bạn khi xuất phát và khi sắp đến để bạn chuẩn bị đón. Với đơn giao tỉnh xa qua xe khách hoặc dịch vụ vận chuyển, shop sẽ cung cấp mã vận đơn và số điện thoại liên lạc của tài xế để bạn có thể hỏi thăm trực tiếp. Shop cũng chủ động liên lạc với điểm nhận hàng để đảm bảo bé được chăm sóc trong hành trình. Nếu bạn lo lắng hoặc chưa nhận được cập nhật trong thời gian dài, hãy nhắn tin cho shop để được kiểm tra ngay. Shop cam kết luôn biết tình trạng của bé trong suốt quá trình vận chuyển nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Ship hàng phụ kiện có khác gì ship mèo không?', N'Ship hàng phụ kiện như thức ăn, đồ chơi, cát vệ sinh hoàn toàn bình thường qua các đơn vị vận chuyển thông thường như GHN, GHTK, J&T với thời gian nhanh và chi phí thấp. Ngược lại, ship mèo sống cần nhiều yêu cầu đặc biệt hơn về nhiệt độ, thông gió, thời gian di chuyển và kinh nghiệm xử lý thú sống. Phí ship mèo vì vậy cao hơn đáng kể. Bạn có thể đặt mèo và phụ kiện kèm theo trong cùng một đơn nhưng shop sẽ tách ra thành hai lô giao hàng riêng để đảm bảo an toàn cho bé. Phụ kiện có thể giao trước để bạn chuẩn bị đầy đủ trước khi bé về nhà nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Cuối tuần và ngày lễ shop có giao hàng phụ kiện không?', N'Có bạn nhé! Meow Garden giao hàng phụ kiện 7 ngày trong tuần kể cả thứ 7 chủ nhật và hầu hết các ngày lễ thông thường. Tuy nhiên dịp Tết Nguyên Đán từ ngày 28 tháng Chạp đến mùng 4 Tết, shop và các đơn vị vận chuyển đối tác sẽ tạm nghỉ. Đơn đặt trong dịp Tết sẽ được xử lý sau kỳ nghỉ. Shop khuyến nghị đặt hàng trữ thức ăn và vật dụng cho mèo ít nhất 1 tuần trước Tết để tránh gián đoạn. Ngoài các dịp Tết, mọi đơn hàng đặt trước 14h đều được xử lý và giao trong ngày hôm sau nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Đơn hàng bị thất lạc trong quá trình vận chuyển thì sao?', N'Nếu đơn hàng phụ kiện bị thất lạc trong quá trình vận chuyển, Meow Garden sẽ liên hệ với đơn vị vận chuyển để tra cứu và xử lý. Nếu sau 7 ngày làm việc vẫn không tìm được hàng, shop sẽ gửi lại đơn hàng mới miễn phí cho bạn. Đối với hàng có giá trị cao, shop sẽ mua bảo hiểm hàng hóa khi giao. Để hỗ trợ nhanh nhất, bạn cần cung cấp mã vận đơn và thông tin liên hệ rõ ràng. Với việc giao mèo sống, shop luôn xác nhận đã giao đến tay người nhận trước khi kết thúc đơn hàng. Hãy liên hệ shop ngay khi phát hiện đơn bị chậm bất thường nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có giao hàng nhanh trong ngày cho thức ăn mèo khẩn cấp không?', N'Có bạn nhé! Với khách tại Hà Nội và TP.HCM, Meow Garden hỗ trợ giao hỏa tốc trong 2-4 giờ cho các đơn thức ăn và phụ kiện thiết yếu. Đơn đặt trước 16h thường được giao trong ngày. Phụ phí giao nhanh khoảng 30-50k tùy khoảng cách. Dịch vụ này đặc biệt hữu ích khi bé mèo bỗng nhiên hết thức ăn hoặc bạn cần thuốc bổ sung gấp. Để đặt giao nhanh, nhắn tin Zalo hoặc gọi hotline của shop và nêu rõ cần giao gấp. Nhân viên sẽ xác nhận khả năng giao và thời gian dự kiến trong vòng 15 phút nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Bao bì đóng gói mèo trong quá trình vận chuyển như thế nào?', N'Meow Garden đặt mèo trong lồng vận chuyển nhựa hoặc vải chuyên dụng có thiết kế thông thoáng nhiều lỗ thoát khí ở bốn mặt. Trong lồng có lót miếng thấm hút hoặc vải mềm để bé thoải mái nằm, kèm đồ chơi quen thuộc hoặc miếng vải có mùi quen giúp bé bớt lo lắng. Với hành trình dài từ 4 tiếng trở lên, shop đặt thêm khay cát nhỏ và bình nước gắn lồng để bé có thể uống nước trong đường đi. Lồng được cố định chắc chắn tránh xô lắc trong phương tiện. Shop không sử dụng thùng kín hoặc bao tải để đóng gói mèo vì đây là vi phạm tiêu chuẩn an toàn động vật nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Ship hàng về vùng núi tỉnh xa có giao được không?', N'Meow Garden giao hàng phụ kiện đến hầu hết địa chỉ trong cả nước thông qua mạng lưới đối tác GHN, GHTK, J&T. Tuy nhiên một số địa điểm vùng sâu vùng xa không có điểm bưu cục gần có thể cần bạn ra điểm thu gom gần nhất để nhận hàng. Thời gian giao đến vùng núi thường 5-7 ngày làm việc. Riêng giao mèo sống đến vùng núi xa shop cần đánh giá cụ thể vì thời gian vận chuyển dài và điều kiện đường xá có thể ảnh hưởng đến sức khỏe bé. Hãy cung cấp địa chỉ đầy đủ cho shop để được báo giá và thời gian giao chính xác nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Có thể nhờ người khác nhận mèo hộ không?', N'Hoàn toàn có thể bạn nhé! Nếu bạn không có mặt để nhận mèo trực tiếp, bạn có thể nhờ người thân hoặc bạn bè nhận hộ. Cần thông báo trước cho shop tên và số điện thoại người nhận hộ để nhân viên giao hàng có thể liên hệ. Người nhận hộ cần có mặt đúng giờ hẹn và chụp lại tình trạng bé lúc nhận để bạn kiểm tra từ xa. Mọi quyền lợi bảo hành và khiếu nại vẫn áp dụng bình thường dù bạn nhận trực tiếp hay qua người khác. Tuy nhiên shop khuyến nghị bạn có mặt trực tiếp khi nhận mèo nếu được để có thể hỏi thêm thông tin và hướng dẫn chăm sóc từ nhân viên giao hàng nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Giao hàng phụ kiện bị chậm hơn dự kiến phải làm gì?', N'Nếu đơn hàng phụ kiện bị chậm hơn thời gian dự kiến trên hệ thống, bước đầu tiên là kiểm tra tracking code qua ứng dụng của đơn vị vận chuyển. Nếu thấy đơn bị giữ tại kho trung chuyển hoặc có ghi chú bất thường, hãy nhắn tin cho shop kèm mã vận đơn để được hỗ trợ liên hệ đôn đốc. Thông thường đơn trễ có thể do địa chỉ không tìm được, số điện thoại không liên lạc được hoặc tắc nghẽn trong dịp cao điểm. Shop sẽ can thiệp với đơn vị vận chuyển trong vòng 4 giờ làm việc. Nếu đơn trễ quá 5 ngày so với cam kết, shop sẽ có phương án bồi thường phù hợp nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có bán lồng vận chuyển mèo chất lượng không?', N'Meow Garden có bán nhiều loại lồng vận chuyển mèo chất lượng tốt tại shop. Bao gồm lồng nhựa cứng có cửa sắt phù hợp cho mèo từ 2-6kg, lồng vải mềm gấp gọn tiện mang theo trên xe máy và xe hơi, và balo trong suốt cho mèo nhỏ dưới 4kg rất được ưa chuộng. Giá dao động từ 200k đến 600k tùy loại. Shop khuyến nghị mua lồng trước khi nhận mèo và để bé quen dần với lồng tại nhà bằng cách đặt lồng mở ở nơi bé thường nằm. Mèo quen lồng sẽ ít stress hơn nhiều khi cần đến bác sĩ thú y hoặc đi xa. Xem chi tiết sản phẩm trên website nhé!', N'shipping', 1, GETUTCDATE(), GETUTCDATE()),

-- ============================================================
-- ĐẶT HÀNG / THANH TOÁN (40 FAQ) — category: 'order'
-- ============================================================

(N'Thanh toán qua ví điện tử MoMo được không?', N'Có bạn nhé! Meow Garden chấp nhận thanh toán qua ví MoMo cho tất cả các đơn hàng phụ kiện và cọc mèo. Bạn chỉ cần chuyển tiền vào số tài khoản MoMo của shop kèm nội dung chuyển khoản ghi rõ tên và mã đơn hàng. Sau khi nhận được thanh toán, shop sẽ xác nhận và xử lý đơn trong vòng 30 phút trong giờ làm việc. Nếu chuyển ngoài giờ làm việc, đơn sẽ được xác nhận vào sáng hôm sau. Lưu ý giữ lại ảnh chụp màn hình xác nhận giao dịch để đối chiếu nếu cần. Thông tin tài khoản MoMo của shop có thể hỏi nhân viên tư vấn hoặc xem trên fanpage nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Thanh toán qua ZaloPay hoặc VNPay được không?', N'Meow Garden chấp nhận thanh toán qua ZaloPay và VNPay bạn nhé. Đây là các phương thức thanh toán điện tử an toàn và tiện lợi. Khi thanh toán qua các ví này, bạn cần ghi rõ nội dung chuyển khoản bao gồm tên đặt hàng và mã đơn hàng để shop có thể đối chiếu nhanh. Xác nhận đơn sẽ được gửi về cho bạn trong vòng 30 phút sau khi nhận được thanh toán trong giờ làm việc. Nếu bạn gặp lỗi trong quá trình thanh toán online, hãy chụp màn hình lỗi gửi cho shop để được hỗ trợ. Shop luôn cập nhật các phương thức thanh toán mới để tiện lợi nhất cho khách hàng nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có hỗ trợ trả góp mua mèo không?', N'Hiện tại Meow Garden chưa hỗ trợ trả góp chính thức qua ngân hàng hoặc công ty tài chính. Tuy nhiên shop có thể linh hoạt hỗ trợ phương án đặt cọc nhiều lần trong trường hợp bé có giá trị cao. Ví dụ bạn đặt cọc 30% khi đặt mua, thanh toán thêm 30% sau 2 tuần và phần còn lại khi nhận bé. Phương án này cần thỏa thuận trực tiếp với shop và phụ thuộc vào từng trường hợp cụ thể. Nếu bạn thanh toán qua thẻ tín dụng, ngân hàng phát hành thẻ của bạn có thể hỗ trợ trả góp 0% cho giao dịch đủ điều kiện. Shop khuyến nghị liên hệ trực tiếp để thảo luận phương án thanh toán phù hợp nhất với bạn nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có xuất hóa đơn VAT không?', N'Meow Garden có thể xuất hóa đơn VAT theo yêu cầu cho khách doanh nghiệp hoặc cá nhân cần hóa đơn đỏ. Để yêu cầu hóa đơn VAT, bạn cần cung cấp thông tin doanh nghiệp bao gồm tên công ty, mã số thuế và địa chỉ trước khi thanh toán. Shop không xuất hóa đơn sau khi đơn đã hoàn tất. Lưu ý rằng hóa đơn VAT thường chỉ áp dụng cho sản phẩm và dịch vụ, việc xuất hóa đơn cho mèo sống có thể có một số hạn chế pháp lý nhất định. Hãy liên hệ shop trực tiếp để được tư vấn cụ thể về loại hóa đơn phù hợp với nhu cầu của bạn nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Video call xem mèo trước khi đặt mua được không?', N'Hoàn toàn được và shop rất khuyến khích bạn thực hiện video call trước khi đặt mua, đặc biệt với khách ở tỉnh xa không thể đến trực tiếp. Bạn chỉ cần nhắn tin cho shop qua Zalo hoặc Messenger để đặt lịch video call thuận tiện. Trong buổi video call, nhân viên shop sẽ cho bạn xem bé từ nhiều góc độ, quan sát tính cách bé, kiểm tra tình trạng mắt tai lông móng và trả lời mọi câu hỏi của bạn về bé. Video call thường kéo dài 10-20 phút tùy nhu cầu. Sau khi video call nếu bạn hài lòng với bé có thể đặt cọc ngay để giữ bé. Shop sắp xếp video call trong giờ làm việc 8h-20h hàng ngày nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Đặt cọc bao nhiêu phần trăm mới giữ được mèo?', N'Để giữ chỗ một bé mèo tại Meow Garden, bạn cần đặt cọc tối thiểu 30% giá trị của bé. Với mèo giá cao trên 10 triệu, shop yêu cầu đặt cọc 30-50% để đảm bảo nghiêm túc. Tiền cọc thanh toán qua chuyển khoản ngân hàng hoặc VietQR trên website. Sau khi đặt cọc thành công, bé sẽ được giữ riêng tên bạn trong tối đa 14 ngày. Thời hạn giữ cọc có thể gia hạn nếu bạn có lý do chính đáng và thông báo trước. Phần tiền còn lại thanh toán khi nhận bé. Biên lai cọc sẽ được gửi qua Zalo hoặc email ngay sau khi shop xác nhận nhận được tiền nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Sau khi đặt cọc bao lâu thì phải đến nhận mèo?', N'Sau khi đặt cọc, bạn cần nhận bé trong vòng 14 ngày kể từ ngày cọc. Nếu cần thêm thời gian, hãy báo shop trước ít nhất 2 ngày trước khi hết hạn để shop sắp xếp giữ bé thêm. Thời gian gia hạn tối đa thêm 7 ngày. Nếu sau 14 ngày không có thông báo gia hạn và bạn không nhận bé, shop có quyền bán bé cho khách khác và tiền cọc sẽ không được hoàn trả. Trong thời gian giữ cọc, shop sẽ chụp ảnh và cập nhật tình trạng bé cho bạn theo tuần. Hãy lên kế hoạch cụ thể trước khi đặt cọc để tránh mất cọc không đáng nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Áp mã voucher giảm giá khi đặt hàng thế nào?', N'Để áp mã voucher khi đặt hàng trên website Meow Garden, bạn thêm sản phẩm vào giỏ hàng và tiến đến trang thanh toán. Tại trang thanh toán có ô nhập mã voucher, bạn gõ mã chính xác bao gồm cả chữ hoa chữ thường rồi nhấn áp dụng. Nếu mã hợp lệ, số tiền giảm sẽ hiển thị ngay. Lưu ý một số voucher có điều kiện tối thiểu giá trị đơn hàng hoặc chỉ áp dụng cho danh mục cụ thể. Nếu mã không hoạt động, hãy kiểm tra chính tả, hạn sử dụng và điều kiện áp dụng. Mỗi tài khoản thường chỉ được dùng một mã voucher mỗi lần. Nhắn tin shop nếu gặp khó khăn khi áp mã nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mã voucher hết hạn có thể xin gia hạn không?', N'Thông thường mã voucher hết hạn sẽ không được gia hạn vì đây là cam kết thời hạn khuyến mãi của shop. Tuy nhiên trong một số trường hợp đặc biệt như bạn không nhận được thông báo về hạn sử dụng hoặc có lỗi kỹ thuật từ phía hệ thống, shop sẽ xem xét hỗ trợ. Để được xem xét, bạn cần liên hệ shop kèm ảnh chụp màn hình mã voucher và đơn hàng muốn áp dụng trong vòng 48 giờ sau khi mã hết hạn. Shop sẽ không gia hạn nếu mã đã hết hạn từ trước đó nhiều ngày. Cách tốt nhất là theo dõi fanpage và bật thông báo để không bỏ lỡ các đợt khuyến mãi của shop nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Voucher FREESHIP và voucher giảm tiền dùng cùng lúc được không?', N'Tại Meow Garden, thông thường bạn chỉ có thể áp dụng một mã voucher cho mỗi đơn hàng. Voucher FREESHIP và voucher giảm tiền hàng không thể dùng đồng thời. Tuy nhiên trong một số chương trình khuyến mãi đặc biệt, shop có thể cho phép kết hợp voucher, điều này sẽ được ghi rõ trong thông tin chương trình. Nếu đơn hàng của bạn đủ điều kiện miễn phí ship tự động theo chính sách đơn trên 500k, phần miễn ship này không tính là dùng voucher nên bạn vẫn có thể áp thêm voucher giảm tiền hàng. Để biết chính xác voucher nào đang có thể kết hợp, hãy kiểm tra điều kiện ghi trong từng voucher hoặc hỏi nhân viên shop nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Đặt hàng xong muốn thêm sản phẩm vào đơn cũ được không?', N'Sau khi đơn hàng đã được xác nhận và đang xử lý, việc thêm sản phẩm vào cùng đơn rất hạn chế vì hệ thống đã ghi nhận thông tin đóng gói. Bạn có hai lựa chọn: liên hệ ngay shop qua Zalo hoặc điện thoại trong vòng 1-2 giờ sau khi đặt, trước khi đơn được lấy đi. Nếu đơn chưa được lấy, nhân viên có thể xử lý thêm sản phẩm và điều chỉnh tổng tiền. Hoặc đặt đơn mới riêng và nếu hai đơn chưa được giao, shop có thể gộp lại để tiết kiệm phí ship cho bạn. Cách đơn giản nhất là kiểm tra kỹ giỏ hàng trước khi thanh toán để tránh phải chỉnh sửa sau nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Chuyển khoản xong nhưng đơn chưa được xác nhận phải làm gì?', N'Nếu bạn đã chuyển khoản nhưng chưa nhận được xác nhận đơn hàng sau 30 phút trong giờ làm việc, hãy thực hiện các bước sau. Chụp màn hình biên lai chuyển khoản có đầy đủ thông tin số tài khoản nhận, số tiền, thời gian và nội dung chuyển khoản. Sau đó gửi ảnh này kèm thông tin đơn hàng qua Zalo hoặc inbox fanpage của shop. Nhân viên sẽ đối chiếu và xác nhận đơn trong vòng 15 phút. Lỗi thường gặp là nội dung chuyển khoản thiếu mã đơn hàng hoặc chuyển nhầm tài khoản nên khó tìm kiếm tự động. Giữ biên lai chuyển khoản đến khi nhận được hàng để đề phòng trường hợp cần đối chiếu nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Đặt hàng lúc đêm khuya shop có xử lý không?', N'Đơn hàng đặt ngoài giờ làm việc 8h-21h sẽ được tự động lưu lại và xử lý vào sáng hôm sau khi nhân viên bắt đầu làm việc. Bạn vẫn sẽ nhận được email xác nhận đơn tự động ngay lập tức sau khi đặt. Phần xác nhận thủ công và liên lạc từ nhân viên sẽ bắt đầu từ 8h sáng ngày hôm sau. Đơn thanh toán COD không bị ảnh hưởng vì nhân viên sẽ gọi xác nhận vào buổi sáng. Đối với đơn thanh toán online đã được thanh toán, đơn sẽ được ưu tiên xử lý sớm nhất khi bắt đầu giờ làm việc. Đặt hàng lúc đêm rất tiện lợi vì website hoạt động 24/7 nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có bán hàng qua Shopee hoặc Lazada không?', N'Meow Garden hiện chưa có gian hàng chính thức trên Shopee hay Lazada. Để đảm bảo quyền lợi và chất lượng sản phẩm, shop chỉ bán hàng qua website chính thức và các kênh trực tiếp như fanpage Facebook, Zalo và tại shop. Điều này giúp shop kiểm soát chất lượng và đảm bảo đúng chính sách bảo hành đã cam kết. Nếu bạn thấy sản phẩm mang tên Meow Garden trên sàn thương mại điện tử, hãy cẩn thận vì đây không phải gian hàng chính thức. Mua hàng trực tiếp từ kênh chính thức cũng đảm bảo bạn được hưởng đầy đủ các chính sách ưu đãi và hậu mãi của shop nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Giá trên website và giá trực tiếp tại shop có khác nhau không?', N'Giá niêm yết trên website và tại shop trực tiếp của Meow Garden là như nhau. Shop không áp dụng chính sách giá khác nhau cho hai kênh này để đảm bảo công bằng cho tất cả khách hàng. Điểm khác biệt duy nhất là khi mua trực tiếp tại shop bạn có thể xem và chọn bé trực tiếp, trong khi mua online có thêm phí vận chuyển. Đôi khi shop có chương trình khuyến mãi flash sale chỉ áp dụng trên website hoặc ngược lại chỉ dành cho khách mua tại quầy trong một dịp đặc biệt. Thông tin khuyến mãi luôn được thông báo rõ ràng trên fanpage để bạn chủ động nắm bắt cơ hội nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mua nhiều mèo cùng lúc có được giảm giá không?', N'Meow Garden có chính sách ưu đãi cho khách mua từ 2 bé trở lên cùng một lúc. Mức giảm cụ thể phụ thuộc vào giống và giá trị từng bé, thông thường từ 5-15%. Ngoài ra khi mua nhiều bé, phí vận chuyển thường được tính gộp và tiết kiệm hơn so với mua riêng lẻ từng bé. Để được hưởng ưu đãi mua nhiều, bạn cần thông báo trước khi đặt hàng để nhân viên tính toán và áp dụng đúng. Ưu đãi mua nhiều cũng áp dụng khi mua combo mèo kèm gói phụ kiện cơ bản. Liên hệ trực tiếp với shop để được báo giá combo tốt nhất theo nhu cầu của bạn nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mua mèo làm quà tặng sinh nhật shop có hỗ trợ gói quà không?', N'Meow Garden hỗ trợ một số dịch vụ đặc biệt khi bạn mua mèo làm quà tặng. Shop có thể in thẻ chúc mừng kèm thông điệp của bạn, chuẩn bị bao bì và phụ kiện kèm theo đẹp mắt phù hợp để tặng. Ngoài ra shop có thể sắp xếp giao bé đúng ngày sinh nhật hoặc dịp đặc biệt theo yêu cầu. Tuy nhiên shop khuyến nghị chỉ tặng mèo khi biết chắc người nhận thực sự muốn nuôi và có điều kiện chăm sóc lâu dài. Một lựa chọn thay thế là tặng phiếu quà tặng trị giá tiền để người nhận tự đến shop chọn bé mình thích. Liên hệ shop trước ít nhất 3 ngày để chuẩn bị quà tặng đặc biệt nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Đặt hàng qua điện thoại hotline được không?', N'Có bạn nhé! Meow Garden nhận đặt hàng qua điện thoại và Zalo không chỉ qua website. Bạn có thể gọi điện hoặc nhắn tin vào số hotline của shop trong giờ làm việc 8h-21h để đặt hàng trực tiếp với nhân viên tư vấn. Nhân viên sẽ hỗ trợ bạn chọn sản phẩm, xác nhận đơn hàng và hướng dẫn thanh toán qua các hình thức phù hợp. Đặt qua điện thoại đặc biệt thuận tiện khi bạn cần tư vấn thêm về sản phẩm hoặc cần đặt hàng gấp mà không có thời gian vào website. Sau khi xác nhận đơn, bạn sẽ nhận được tin nhắn xác nhận qua Zalo hoặc SMS nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mua mèo có được nhận kèm tài liệu hướng dẫn chăm sóc không?', N'Có bạn nhé! Mỗi bé mèo bán ra tại Meow Garden đều được kèm theo tài liệu hướng dẫn chăm sóc cơ bản bằng tiếng Việt. Tài liệu này bao gồm hướng dẫn cho ăn theo độ tuổi, lịch tiêm phòng và tẩy giun, cách vệ sinh và chải lông, các dấu hiệu bệnh cần đi khám và danh sách thứ gì không được cho mèo ăn hoặc tiếp xúc. Ngoài tài liệu in, shop cũng gửi link vào nhóm cộng đồng chủ mèo Meow Garden trên Zalo nơi bạn có thể hỏi kinh nghiệm và nhận cập nhật thường xuyên. Với khách mua lần đầu, nhân viên sẽ dành thêm thời gian tư vấn chi tiết về chăm sóc bé nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mua combo mèo và phụ kiện có tiết kiệm hơn không?', N'Meow Garden có các gói combo mèo kèm phụ kiện cơ bản với mức giá ưu đãi hơn so với mua lẻ từng thứ. Gói cơ bản thường bao gồm mèo kèm khay cát, 1 túi cát vệ sinh, 1 túi hạt thức ăn dùng thử 2 tuần và bát ăn. Gói nâng cao có thể bổ sung thêm đồ chơi, cào móng và carrier. Tiết kiệm trung bình 15-25% so với mua riêng lẻ. Đây là lựa chọn rất phù hợp cho người nuôi mèo lần đầu vì đảm bảo đủ đồ dùng thiết yếu ngay từ ngày đầu. Hỏi nhân viên shop về các gói combo hiện có và giá cụ thể, shop có thể tùy chỉnh gói theo nhu cầu của bạn nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Đặt cọc qua chuyển khoản nhưng chưa thấy xác nhận sau 30 phút phải làm gì?', N'Nếu sau 30 phút chuyển khoản đặt cọc bạn chưa nhận được xác nhận, đầu tiên kiểm tra lại nội dung chuyển khoản xem có ghi rõ tên và thông tin mèo muốn đặt cọc chưa. Sau đó chụp màn hình biên lai chuyển khoản từ app ngân hàng có đầy đủ thông tin giao dịch. Gửi ảnh biên lai kèm thông tin cần đặt cọc bé nào qua Zalo hoặc inbox fanpage của shop. Nhân viên sẽ xác nhận thủ công trong vòng 15 phút sau khi nhận được thông tin. Đôi khi hệ thống thông báo tự động có độ trễ nhất định nên cần kiểm tra hộp thư rác email. Trong giờ cao điểm cuối tuần có thể chậm hơn một chút nhưng shop đảm bảo xác nhận mọi đặt cọc nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Có thể đặt nhiều bé mèo khác nhau và chọn một bé sau không?', N'Meow Garden không cho phép đặt cọc nhiều bé cùng lúc để chọn một bé sau vì điều này ảnh hưởng không công bằng đến cơ hội của khách hàng khác. Mỗi lần bạn chỉ được đặt cọc một bé. Nếu bạn muốn so sánh nhiều bé trước khi quyết định, shop khuyến nghị đặt lịch video call hoặc đến xem trực tiếp các bé bạn quan tâm trước, sau đó mới đặt cọc bé đã chọn. Bạn có thể xem nhiều bé trong cùng một buổi video call để tiết kiệm thời gian. Nếu sau khi cân nhắc bạn muốn đổi sang bé khác và bé đó vẫn còn, shop sẽ xem xét điều chỉnh đặt cọc trong vòng 24 giờ nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Hủy đơn sản phẩm phụ kiện sau khi thanh toán online được không?', N'Đơn hàng phụ kiện chưa được lấy bởi đơn vị vận chuyển vẫn có thể hủy và hoàn tiền đầy đủ. Bạn cần liên hệ shop trong vòng 2 giờ sau khi đặt hàng để được xử lý kịp thời. Sau khi đơn đã được lấy bởi shipper, bạn có thể từ chối nhận hàng, khi đó hàng sẽ được hoàn về shop và shop sẽ hoàn tiền trừ phí vận chuyển hai chiều. Đối với đơn hàng đã nhận nhưng muốn trả, sản phẩm cần còn nguyên vẹn chưa mở bao bì và trong vòng 3 ngày nhận hàng theo chính sách đổi trả của shop. Liên hệ hotline hoặc Zalo shop để được hướng dẫn quy trình hủy đơn nhanh nhất nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Đặt mèo theo yêu cầu giống cụ thể mà không có sẵn thì sao?', N'Nếu giống mèo bạn muốn hiện không có sẵn tại Meow Garden, shop sẽ ghi nhận yêu cầu của bạn vào danh sách chờ. Khi có nguồn bé phù hợp từ trại giống đối tác, shop sẽ ưu tiên thông báo ngay cho bạn. Bạn không bắt buộc phải đặt cọc để vào danh sách chờ. Thời gian chờ trung bình từ 1-6 tháng tùy giống phổ biến hay hiếm. Trong thời gian chờ, shop có thể giới thiệu các giống tương tự có đặc điểm gần giống yêu cầu của bạn nếu muốn. Đăng ký danh sách chờ hoàn toàn miễn phí và bạn có quyền từ chối bé khi được thông báo mà không có ràng buộc gì nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Thanh toán COD bị nhân viên giao hàng yêu cầu tiền thêm có đúng không?', N'Không đúng bạn nhé! Nhân viên giao hàng của Meow Garden hoặc đối tác vận chuyển không được phép yêu cầu bất kỳ khoản tiền nào ngoài số tiền COD đã xác nhận trên đơn hàng. Nếu bạn gặp tình huống này, hãy từ chối thanh toán khoản phụ thu và liên hệ ngay với shop qua điện thoại để được xác nhận. Shop sẽ xử lý nghiêm nếu phát hiện nhân viên thu sai. Số tiền COD chính xác sẽ được ghi rõ trong SMS xác nhận đơn hàng trước khi giao. Bạn có quyền yêu cầu xem lại thông tin đơn hàng nếu có thắc mắc về số tiền nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có chương trình giới thiệu bạn bè nhận ưu đãi không?', N'Meow Garden có chương trình referral dành cho khách hàng đã mua hàng tại shop. Khi bạn giới thiệu bạn bè mua mèo hoặc phụ kiện lần đầu và đơn hàng thành công, bạn sẽ nhận được voucher giảm giá hoặc điểm thưởng cho lần mua tiếp theo. Chương trình này là lời cảm ơn của shop đối với khách hàng thân thiết đã tin tưởng và giới thiệu thêm bạn bè. Để tham gia, bạn cần báo cho nhân viên biết bạn bè được giới thiệu bởi ai khi mua. Chi tiết điều kiện và mức ưu đãi cụ thể xem trên fanpage hoặc hỏi nhân viên shop. Cảm ơn bạn đã lan tỏa tình yêu mèo cùng Meow Garden nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Đặt hàng trên website có an toàn không, thông tin của tôi có bị lộ không?', N'Website Meow Garden sử dụng giao thức bảo mật HTTPS và mã hóa dữ liệu để bảo vệ thông tin cá nhân của bạn. Thông tin như tên, địa chỉ và số điện thoại chỉ được dùng để xử lý đơn hàng và giao hàng, không được chia sẻ cho bên thứ ba không liên quan. Thanh toán online được thực hiện qua cổng thanh toán bảo mật, thông tin thẻ ngân hàng không được lưu trên hệ thống của shop. Bạn có thể yên tâm đặt hàng online. Nếu muốn đặt hàng mà không để lại thông tin online, bạn cũng có thể liên hệ trực tiếp qua điện thoại để đặt hàng và thanh toán theo cách bạn thấy thoải mái nhất nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Giao hàng ngày lễ Tết có bị gián đoạn không?', N'Dịp Tết Nguyên Đán là thời điểm shop và hầu hết đơn vị vận chuyển nghỉ Tết từ ngày 28-30 tháng Chạp đến mùng 4-5 Tết. Đơn đặt trong giai đoạn này sẽ được giao sau kỳ nghỉ. Ngoài Tết Nguyên Đán, shop vẫn hoạt động bình thường trong hầu hết các ngày lễ còn lại như 30/4, 1/5, 2/9, mặc dù một số ngày có thể giảm nhân sự và thời gian xử lý đơn chậm hơn một chút. Shop luôn thông báo trước trên fanpage về lịch nghỉ để bạn chủ động đặt hàng sớm. Đặc biệt trước Tết shop khuyến nghị đặt thức ăn và vật dụng cho mèo ít nhất 1 tuần để đảm bảo không thiếu trong kỳ nghỉ nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Giá mèo trên website có bao gồm phí vận chuyển không?', N'Giá mèo hiển thị trên website Meow Garden là giá bé tại shop, chưa bao gồm phí vận chuyển. Phí vận chuyển sẽ được tính thêm dựa trên địa chỉ nhận hàng và phương thức giao. Với khách nội thành Hà Nội và TP.HCM, phí giao dao động 50-100k. Với tỉnh xa, phí sẽ được báo cụ thể khi bạn xác nhận đặt hàng. Trong một số chương trình khuyến mãi, shop có thể hỗ trợ miễn phí ship cho đơn mèo. Giá phụ kiện từ 500k trở lên được miễn phí ship nội thành theo chính sách thông thường. Trước khi thanh toán, tổng số tiền bao gồm cả phí ship sẽ được hiển thị rõ ràng để bạn xem xét nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Nhận hàng xong phát hiện sai sản phẩm phải làm gì?', N'Nếu nhận hàng phụ kiện không đúng với những gì bạn đặt, hãy thực hiện ngay các bước sau. Đầu tiên không mở bao bì sản phẩm sai và chụp ảnh sản phẩm nhận được kèm hóa đơn giao hàng. Liên hệ shop trong vòng 24 giờ sau khi nhận hàng kèm ảnh chứng minh. Shop sẽ xác nhận lỗi và sắp xếp đổi hàng đúng miễn phí bao gồm cả phí vận chuyển hai chiều trong trường hợp lỗi từ phía shop. Thời gian xử lý thường 1-3 ngày làm việc. Với sản phẩm giao sai, shop cam kết giải quyết 100% và đảm bảo bạn nhận được đúng hàng đã đặt. Xin lỗi vì bất tiện này và shop sẽ cố gắng không để xảy ra lần sau nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Đặt cọc online có an toàn không, nếu shop lừa đảo thì sao?', N'Meow Garden là shop mèo uy tín đã hoạt động nhiều năm với hàng nghìn khách hàng hài lòng và hàng trăm đánh giá tốt trên fanpage. Để đảm bảo an toàn khi đặt cọc online, bạn có thể kiểm tra fanpage và đọc nhận xét của khách hàng cũ, yêu cầu gặp mặt trực tiếp tại shop trước khi đặt cọc, hoặc đặt cọc qua VietQR trên website chính thức thay vì chuyển khoản cá nhân. Shop cũng có địa chỉ cụ thể và nhân viên sẵn sàng gặp trực tiếp. Nếu bạn vẫn chưa yên tâm, đến xem bé trực tiếp rồi mới thanh toán tại chỗ là cách an toàn nhất. Shop không ép bạn đặt cọc từ xa nếu bạn không thoải mái nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Shop có nhận đổi sản phẩm phụ kiện đã mở hộp không?', N'Meow Garden hỗ trợ đổi sản phẩm phụ kiện trong vòng 3 ngày kể từ ngày nhận hàng nếu sản phẩm có lỗi kỹ thuật từ nhà sản xuất như motor bơm nước không hoạt động, dây kéo bị đứt ngay khi mở hộp, hoặc sản phẩm không đúng như mô tả. Điều kiện đổi hàng là sản phẩm phải còn đầy đủ phụ kiện và hộp đựng kể cả đã mở. Với lý do không thích sau khi sử dụng, shop không áp dụng đổi trả vì đây là đặc thù của sản phẩm đã dùng. Hãy xem kỹ thông tin sản phẩm trước khi mua và hỏi nhân viên nếu có thắc mắc để tránh mua sai sản phẩm nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Thanh toán bằng thẻ ngân hàng quốc tế Visa Mastercard được không?', N'Hiện tại thanh toán trực tiếp bằng thẻ Visa Mastercard quốc tế chưa được tích hợp vào hệ thống thanh toán của Meow Garden. Tuy nhiên bạn có thể thanh toán qua VNPay hoặc cổng thanh toán trực tuyến hỗ trợ thẻ quốc tế nếu tài khoản ngân hàng của bạn liên kết với ví điện tử. Ngoài ra, nếu bạn là khách nước ngoài hoặc Việt kiều muốn mua mèo, hãy liên hệ trực tiếp với shop để được tư vấn phương thức thanh toán phù hợp nhất. Shop luôn cố gắng tìm giải pháp thanh toán thuận tiện nhất cho mọi khách hàng nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mua mèo rồi cần mua thêm phụ kiện gì là bắt buộc?', N'Để nuôi mèo an toàn và thoải mái, bạn cần chuẩn bị một số vật dụng thiết yếu không thể thiếu. Đầu tiên là khay vệ sinh kèm cát mèo, mỗi con cần ít nhất một khay. Tiếp theo là bát ăn và bát uống nước riêng biệt. Thức ăn phù hợp theo độ tuổi gồm hạt khô và pate. Lồng hoặc carrier để đưa mèo đến bác sĩ thú y. Cào móng hoặc trụ cào để bảo vệ đồ đạc trong nhà. Và ít nhất một đồ chơi để kích thích vận động và giảm stress. Ngoài ra, ổ nằm ấm áp và chỗ trú ẩn nhỏ giúp bé cảm thấy an toàn hơn trong giai đoạn đầu. Meow Garden có đầy đủ tất cả những thứ này nhé!', N'order', 1, GETUTCDATE(), GETUTCDATE());

-- ============================================================
-- BỔ SUNG 12 FAQ (212 tổng) — tổng hợp nhiều chủ đề
-- ============================================================

INSERT INTO Faqs (Question, Answer, Category, IsActive, CreatedAt, UpdatedAt) VALUES

(N'Mèo có cần uống sữa không?', N'Ngược lại với quan niệm phổ biến, hầu hết mèo trưởng thành đều không dung nạp được lactose trong sữa bò và có thể bị tiêu chảy hoặc đau bụng nếu uống sữa thường xuyên. Mèo con dưới 4 tuần tuổi cần sữa mẹ hoặc sữa thay thế chuyên dụng cho mèo con, tuyệt đối không dùng sữa bò. Từ sau cai sữa, nguồn nước tốt nhất cho mèo là nước lọc sạch cung cấp liên tục. Nếu bạn muốn cho mèo thưởng thức sữa, hãy chọn loại sữa không lactose dành riêng cho mèo có bán tại Meow Garden. Đảm bảo mèo luôn có nước uống sạch là điều quan trọng nhất để bảo vệ sức khỏe thận của bé nhé!', N'health', 1, GETUTCDATE(), GETUTCDATE()),

(N'Bao lâu thì nên tắm cho mèo một lần?', N'Mèo là loài tự vệ sinh rất giỏi nên không cần tắm thường xuyên như chó. Với mèo lông ngắn khỏe mạnh, tắm 1-2 tháng một lần là đủ hoặc chỉ tắm khi bé bẩn thực sự. Mèo lông dài như Ba Tư hay Anh lông dài nên tắm mỗi 2-4 tuần kết hợp với chải lông hàng ngày để tránh rối lông. Mèo con dưới 3 tháng tuổi tránh tắm nước, thay vào đó dùng khăn ẩm lau nhẹ. Khi tắm nên dùng dầu gội chuyên dụng cho mèo, không dùng dầu gội người vì pH khác nhau có thể gây kích ứng da. Sau tắm sấy khô hoàn toàn, tránh để bé bị lạnh đặc biệt vào mùa đông nhé!', N'health', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mèo có thể ăn thức ăn của người không?', N'Một số thức ăn của người an toàn cho mèo như thịt gà luộc không xương không gia vị, cá hấp không muối, hoặc một ít rau luộc. Tuy nhiên nhiều loại thực phẩm rất nguy hiểm với mèo gồm hành tỏi gây phá hủy hồng cầu, nho và nho khô gây suy thận, chocolate và caffeine gây ngộ độc thần kinh, xương nhỏ dễ gây hóc và thủng ruột. Muối và đường dù không độc nhưng không tốt cho thận và răng của mèo. Thức ăn có gia vị đậm cũng không phù hợp với hệ tiêu hóa nhạy cảm của mèo. Tốt nhất là cho mèo ăn thức ăn chuyên dụng được cân bằng dinh dưỡng và thi thoảng thưởng thêm thức ăn tươi an toàn với lượng nhỏ nhé!', N'health', 1, GETUTCDATE(), GETUTCDATE()),

(N'Làm sao nhận biết mèo đang bị bệnh?', N'Có một số dấu hiệu cảnh báo quan trọng cho thấy mèo đang không khỏe mà bạn cần chú ý. Bỏ ăn hoặc ăn ít hơn 50% so với bình thường trong 24 giờ là dấu hiệu đáng lo. Nôn mửa nhiều hơn 2 lần trong ngày hoặc có máu trong nôn. Tiêu chảy hoặc táo bón kéo dài. Thở khó, thở miệng hoặc thở nhanh bất thường. Mắt và mũi chảy dịch, mắt nheo hoặc đỏ. Lờ đờ, không chơi, ẩn náu liên tục. Đi tiểu ít, đi tiểu ngoài khay vệ sinh hoặc có máu trong nước tiểu. Bụng to bất thường hoặc đau khi sờ. Nếu thấy bất kỳ dấu hiệu nào trên, hãy đưa mèo đến thú y càng sớm càng tốt để được chẩn đoán và điều trị kịp thời nhé!', N'health', 1, GETUTCDATE(), GETUTCDATE()),

(N'Cát vệ sinh nào tốt nhất cho mèo?', N'Meow Garden cung cấp nhiều loại cát vệ sinh phù hợp với nhu cầu khác nhau. Cát đất sét bentonite là lựa chọn phổ biến nhất, vón cục tốt, dễ dọn, giá cả phải chăng và hầu hết mèo đều thích. Cát đậu phụ làm từ bã đậu nành thân thiện với môi trường, ít bụi, an toàn nếu mèo vô tình liếm, nhưng giá cao hơn và vón cục kém hơn. Cát silica gel hút ẩm tốt, kiểm soát mùi lâu nhưng không phân hủy sinh học và một số mèo không thích cảm giác dưới chân. Cát gỗ thông hoặc cát tre tự nhiên ít bụi và thân thiện môi trường nhưng vón cục kém. Với mèo mới về nhà, nên dùng loại cát bé đã quen để tránh stress và thay đổi dần nếu muốn đổi loại khác nhé!', N'product', 1, GETUTCDATE(), GETUTCDATE()),

(N'Máy uống nước cho mèo có thực sự cần thiết không?', N'Máy uống nước hay fountain nước cho mèo không phải thiết bị bắt buộc nhưng mang lại nhiều lợi ích đáng kể. Mèo trong tự nhiên ưa uống nước chảy hơn nước đứng vì bản năng cho rằng nước chảy sạch hơn, nên fountain kích thích mèo uống nhiều hơn đáng kể. Uống đủ nước rất quan trọng với mèo đặc biệt mèo ăn hạt khô vì giúp ngăn ngừa sỏi thận và bệnh đường tiết niệu. Nếu mèo của bạn hay uống ít nước, thường xuyên mắc bệnh thận hoặc tiết niệu, thì fountain nước là khoản đầu tư rất đáng. Meow Garden có nhiều mẫu fountain từ đơn giản đến cao cấp với bộ lọc thay được. Nếu mèo bạn uống đủ nước từ bát thường thì không cần thiết mua fountain nhé!', N'product', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mèo mới về nhà hay trốn và bỏ ăn là bình thường không?', N'Hoàn toàn bình thường! Mèo là loài rất nhạy cảm với môi trường mới. Trong 3-7 ngày đầu, hầu hết mèo sẽ trốn dưới gầm giường hoặc góc khuất, ăn ít hơn bình thường, không chịu chơi và có thể kêu nhiều. Đây là phản ứng stress hoàn toàn tự nhiên khi bé đang làm quen với mùi hương, âm thanh và người lạ trong môi trường mới. Cách xử lý tốt nhất là để bé tự khám phá không gian theo tốc độ của mình, không cố bắt hay ép bé tiếp xúc, đặt thức ăn và nước gần chỗ bé trốn, nói chuyện nhẹ nhàng để bé quen giọng bạn. Sau 1-2 tuần bé sẽ dần thoải mái và thể hiện đúng tính cách thật. Nếu sau 5 ngày bé vẫn hoàn toàn không ăn gì, hãy liên hệ shop hoặc thú y để được tư vấn nhé!', N'care', 1, GETUTCDATE(), GETUTCDATE()),

(N'Cách vệ sinh tai cho mèo đúng cách như thế nào?', N'Vệ sinh tai mèo định kỳ giúp ngăn ngừa viêm tai và ký sinh trùng tai. Tai mèo khỏe mạnh có màu hồng nhạt, không có mùi và ít ráy tai. Kiểm tra tai mỗi 1-2 tuần, chỉ vệ sinh khi thấy có ráy tai màu nâu nhạt tích tụ. Cách làm: nhỏ vài giọt dung dịch vệ sinh tai chuyên cho mèo vào ống tai, xoa nhẹ gốc tai khoảng 30 giây để chất lỏng làm lỏng ráy tai, rồi dùng bông gòn lau nhẹ phần tai có thể nhìn thấy. Tuyệt đối không dùng tăm bông đưa sâu vào ống tai. Nếu thấy ráy tai màu đen đặc, tai có mùi hôi, mèo hay gãi tai hoặc lắc đầu liên tục thì có thể bị viêm tai hoặc mạt tai, cần đến thú y nhé!', N'care', 1, GETUTCDATE(), GETUTCDATE()),

(N'Có thể nuôi mèo và chó chung một nhà không?', N'Hoàn toàn có thể nuôi mèo và chó cùng nhà nếu được giới thiệu đúng cách và kiên nhẫn. Bí quyết thành công là giới thiệu từ từ, không vội. Trong tuần đầu giữ hai bé tách biệt hoàn toàn nhưng cho ngửi mùi của nhau qua khe cửa hoặc trao đổi chăn gối. Tuần thứ hai cho gặp mặt gián tiếp qua cửa kính hoặc cửa lưới. Tuần thứ ba trở đi cho gặp nhau trực tiếp có giám sát với chó được dắt dây. Không bao giờ để chúng gặp nhau một mình khi chưa quen. Mèo luôn cần có không gian trú ẩn cao mà chó không với tới. Thường thì mèo con và chó con dễ làm quen nhau hơn. Giống chó có bản năng săn mồi cao như Husky hay Greyhound cần thêm thời gian và sự giám sát kỹ càng hơn nhé!', N'care', 1, GETUTCDATE(), GETUTCDATE()),

(N'Nên chọn mèo đực hay mèo cái?', N'Lựa chọn mèo đực hay cái phụ thuộc vào sở thích và hoàn cảnh của bạn. Mèo đực chưa triệt sản thường hiếu động, thân thiện và tình cảm hơn nhưng có xu hướng đánh dấu lãnh thổ bằng nước tiểu và hay bỏ đi khi đến mùa. Mèo cái chưa triệt sản dịu dàng hơn nhưng khi động dục sẽ kêu rất to liên tục và có thể mang thai ngoài ý muốn. Sau khi triệt sản, sự khác biệt giữa đực và cái giảm đi đáng kể. Mèo đực triệt sản thường vẫn giữ được tính cách thân thiện, cởi mở. Mèo cái triệt sản thường điềm tĩnh và độc lập hơn một chút. Cả hai đều có thể trở nên gắn bó sâu sắc với chủ. Meow Garden khuyến nghị triệt sản cho tất cả mèo nuôi nhà vì tốt cho sức khỏe và hành vi của bé nhé!', N'cat', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mèo của tôi hay cào đồ đạc trong nhà, phải làm gì?', N'Cào là hành vi bình thường và cần thiết của mèo giúp mài móng, kéo giãn cơ và đánh dấu lãnh thổ, bạn không thể ngăn hoàn toàn nhưng có thể hướng hành vi này đúng chỗ. Giải pháp hiệu quả nhất là cung cấp nhiều trụ cào hoặc tấm cào đặt ở những nơi mèo hay cào đồ. Trụ cào cần đủ cao để mèo có thể duỗi người hoàn toàn khi cào. Khi thấy mèo cào sai chỗ, nhẹ nhàng bế bé đến trụ cào và hướng dẫn. Có thể dùng catnip xịt lên trụ cào để thu hút bé. Dán băng keo hai mặt hoặc tấm nhựa lên góc ghế sofa hay cạnh cửa mèo hay cào cũng có hiệu quả tốt vì mèo không thích cảm giác dính. Tuyệt đối không phạt hay la mắng bé vì sẽ gây stress và không giải quyết được vấn đề nhé!', N'care', 1, GETUTCDATE(), GETUTCDATE()),

(N'Mèo bị rụng lông nhiều có đáng lo không?', N'Mèo rụng lông theo mùa là hoàn toàn bình thường, thường nhiều nhất vào mùa xuân và thu khi thay lông. Tuy nhiên rụng lông có thể là dấu hiệu cần chú ý trong một số trường hợp. Rụng lông thành mảng hói hoặc rụng kèm ngứa gãi nhiều có thể do nấm da, ghẻ hoặc dị ứng. Rụng lông nhiều bất thường kèm gầy yếu, bỏ ăn có thể liên quan đến vấn đề nội tiết hoặc bệnh lý nghiêm trọng. Rụng lông do stress cũng xảy ra khi mèo thay đổi môi trường hoặc có xung đột với thú cưng khác. Để giảm rụng lông sinh lý, hãy chải lông cho mèo đều đặn mỗi ngày, cung cấp thức ăn đủ axit béo omega, và đảm bảo mèo uống đủ nước. Nếu rụng lông kèm theo bất kỳ triệu chứng bất thường nào, hãy đưa bé đi khám thú y nhé!', N'health', 1, GETUTCDATE(), GETUTCDATE());
